name: Retry OCI Instance Creation

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  create-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install --no-progress
      - name: Create .env file
        run: |
          echo "OCI_REGION='${{ secrets.OCI_REGION }}'" >> .env
          echo "OCI_USER_ID='${{ secrets.OCI_USER_ID }}'" >> .env
          echo "OCI_TENANCY_ID='${{ secrets.OCI_TENANCY_ID }}'" >> .env
          echo "OCI_KEY_FINGERPRINT='${{ secrets.OCI_KEY_FINGERPRINT }}'" >> .env
          echo "OCI_PRIVATE_KEY_FILENAME='${{ secrets.OCI_PRIVATE_KEY_FILENAME }}'" >> .env
          echo "OCI_SUBNET_ID='${{ secrets.OCI_SUBNET_ID }}'" >> .env
          echo "OCI_IMAGE_ID='${{ secrets.OCI_IMAGE_ID }}'" >> .env
          echo "OCI_SSH_PUBLIC_KEY='${{ secrets.OCI_SSH_PUBLIC_KEY }}'" >> .env
          echo "OCI_SHAPE='${{ secrets.OCI_SHAPE }}'" >> .env
      - name: Run script
        run: php index.php
